services:
   portal:
     image: registry.ac.gov.br/sead/portais:latest
     cpus: 1              # Define 1 CPU
     mem_limit: 768m        # Define 768MB de memória
     container_name: ${NOME_ORGAO}-wp
     volumes:
       - /srv/${NOME_PORTAL}.ac.gov.br/wordpress_files:/var/www/html                      
       - /srv/arquivos_parametros/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     ports:
       - "${PORTA_APP}:80"
     restart: always
     networks: 
       - portal_estado_default
volumes:
    wordpress_files:
networks:
  portal_estado_default:
    external: true