version: '3.3'
services:
   portal:
     image: registry.ac.gov.br/sead/portais:latest
     cpus: '1'              # Define 1 CPU
     mem_limit: 768m        # Define 768MB de memória
     container_name: ${NOME_ORGAO}-wp
     volumes:
       - /srv/${NOME_PORTAL}.ac.gov.br/wordpress_files:/var/www/html                      
       - /srv/arquivos_parametros/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     ports:
       - "${PORTA_APP}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: 10.1.6.91:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: Jg_d93Lm
       WORDPRESS_DB_NAME: portal_${NOME_PORTAL}
       WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${NOME_PORTAL}.ac.gov.br');
        define('WP_SITEURL', 'https://${NOME_PORTAL}.ac.gov.br');
volumes:
    wordpress_files: